spring:
  datasource:
    url: jdbc:mysql://oction-rdb.cmtm4w2q8rts.ap-northeast-2.rds.amazonaws.com/weather_db_test
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: admin
    username: ENC(mjc9PGfUO514Zkj3x41KNA==)
    password: ENC(gnuCkyJRZ73tFycAFkMGsCS6BuF4Y2Az)
  #    password: sj991209
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    username: ENC(IDdd/EqGT8hyHUX7chZTOQ9BbJfnWbm7)
#    password: ENC(IgFTdDFO/Wqr7UamoziAnhsIEAIXDk6p)